
import React from "react";
import { motion } from "framer-motion";
import { AlertCircle } from "lucide-react";

const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="py-20 relative overflow-hidden">
      <div className="absolute inset-0 grid-pattern opacity-10 z-0"></div>
      
      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="text-center mb-16">
          <motion.h2 
            className="section-heading mb-6"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
          >
            Legal Disclaimer
          </motion.h2>
          <motion.p 
            className="text-xl text-gray-400 max-w-3xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            viewport={{ once: true }}
          >
            Important information regarding the use of Global Peace Restoration GPT.
          </motion.p>
        </div>
        
        <motion.div 
          className="max-w-4xl mx-auto glass rounded-lg p-8 border border-cyber-red/30"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          viewport={{ once: true }}
        >
          <div className="flex items-center mb-6">
            <AlertCircle className="w-6 h-6 text-cyber-red mr-2" />
            <h3 className="text-xl font-bold text-white">Please Read Carefully</h3>
          </div>
          
          <div className="space-y-6 text-gray-300">
            <p>
              Global Peace Restoration GPT ("the Tool") is an artificial intelligence-based service provided by AI WEB TOOLS LLC for informational and educational purposes only. By accessing or using the Tool, you acknowledge and agree to the following terms:
            </p>
            
            <div>
              <h4 className="font-bold mb-2 text-white">No Professional Advice</h4>
              <p className="text-sm">
                The Tool does not provide professional diplomatic, legal, political, or security advice. The analysis, recommendations, and strategies generated by the Tool should not be construed as professional advice, and users should not rely solely on the Tool for making critical decisions related to actual conflict situations.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">Limitation of Liability</h4>
              <p className="text-sm">
                AI WEB TOOLS LLC and its affiliates, partners, officers, directors, employees, and agents shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with the use of the Tool or the information it provides, even if advised of the possibility of such damages.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">No Warranties</h4>
              <p className="text-sm">
                The Tool is provided "as is" and "as available" without any warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">Data Accuracy</h4>
              <p className="text-sm">
                While we strive to ensure the accuracy and reliability of the information and analysis provided by the Tool, we make no guarantees regarding the completeness, reliability, or accuracy of such information. The Tool processes information available at the time of use and may not reflect the most current data.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">Third-Party Content</h4>
              <p className="text-sm">
                The Tool may access or reference third-party content, websites, or services. We do not endorse, control, or assume responsibility for any third-party content or services accessed through the Tool.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">Use Responsibility</h4>
              <p className="text-sm">
                Users are solely responsible for how they use the information provided by the Tool. The Tool should be used as a supplementary resource in conflict analysis and resolution processes, not as the sole decision-making authority.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">Sensitive Information</h4>
              <p className="text-sm">
                Users should exercise caution when inputting sensitive information related to ongoing conflicts or diplomatic efforts. While we implement reasonable security measures, no system can guarantee absolute security.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2 text-white">Governing Law</h4>
              <p className="text-sm">
                This disclaimer shall be governed by and construed in accordance with the laws of the jurisdiction in which AI WEB TOOLS LLC operates, without regard to its conflict of law provisions.
              </p>
            </div>
            
            <p className="text-sm">
              By using Global Peace Restoration GPT, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. If you do not agree with any part of this disclaimer, please refrain from using the Tool.
            </p>
            
            <p className="text-sm font-bold">
              Last updated: June 1, 2025
            </p>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
